[package]
name = "rust-rest-api"
version = "0.0.2"
authors = [ "Agung Dwi Prasetyo <agungdwiprasetyo22@gmail.com>" ]
edition = "2018"

[dependencies]
actix = "0.10.0-alpha.2"
actix-web = "2.0"
serde = "1.0.106"
dotenv = "0.15.0"
