[package]
name = "rust-rest-api"
version = "0.0.1"
authors = [ "Agung Dwi Prasetyo <agungdwiprasetyo22@gmail.com>" ]

[dependencies]
rocket = "0.4.0-rc.1"
rocket_codegen = "0.4.0-rc.1"
rocket_contrib = "0.4.0-rc.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"